# Generated by Django 4.2.15 on 2024-08-29 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_product'),
        ('products', '0003_item_section_sectionitems_remove_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='sectionitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sections', to='products.item'),
        ),
        migrations.AddField(
            model_name='sectionitems',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='products.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='products.category'),
        ),
        migrations.AddField(
            model_name='section',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='sections', through='products.SectionItems', to='products.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_section', to='products.section'),
        ),
    ]
