# Generated by Django 4.2.15 on 2024-09-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_slug'),
    ]

    operations = [
    ]
