# Generated by Django 4.2.15 on 2024-09-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_populate_category_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
